accounts:
  - name: alice
    coins: ["20000token", "200000000arkh"]
  - name: bob
    coins: ["10000token", "1000000yummy","500000000arkh"]
  - name: arkhadian
    coins: ["100000000arkh"]
    address: "arkh1newxhd7nxtg3xhkaf7hcqxzcf5zmh2zq0ydwda"	
validator:
  name: alice
  staked: "100000000arkh"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["10000token", "500000000arkh"]

genesis:
  app_state:
    staking:
      params:
        bond_denom: "arkh"

init:
  app:
    minimum-gas-prices: "1arkh"